name: Build IntelliJ Plugin

on:
  push:
    branches: [ "master" ]
    paths: ["src/**"]
  pull_request:
    branches: [ "master", "210" ]
    paths: ["src/**"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Cache IntelliJ Sandbox
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/JetBrains/IntelliJIdea*
            ~/.local/share/JetBrains/IntelliJIdea*
          key: intellij-${{ runner.os }}-${{ hashFiles('build.gradle*', 'gradle.properties') }}
          restore-keys: |
            intellij-${{ runner.os }}-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Plugin
        run: ./gradlew buildPlugin --no-daemon
